CREATE DATABASE IF NOT EXISTS portfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE portfolio;
CREATE TABLE IF NOT EXISTS updates (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(160) NOT NULL, status VARCHAR(100), date_info VARCHAR(160), description_title VARCHAR(255), description TEXT, link VARCHAR(255), link_text VARCHAR(100), sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS internship_logs (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, week VARCHAR(50) NOT NULL, date_info VARCHAR(160), title VARCHAR(255), content JSON NOT NULL, gif VARCHAR(500), sort_order INT DEFAULT 0);
